name: "Jest Coverage Report"
description: "Comments a pull request with the jest code coverage"
author: "Raverdy Thomas"
branding:
  icon: "activity"
  color: "green"
inputs:
  github-token:
    description: "Github token"
    required: true
  test-command:
    description: "Specify a command to run the tests"
    required: false
runs:
  using: "node12"
  main: "index.js"